# Generated by Django 4.1.3 on 2022-12-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_fishcount"),
    ]

    operations = [
        migrations.AddField(
            model_name="fish1",
            name="image",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
