# Generated by Django 4.1.3 on 2022-12-29 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_fish1_user2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fish1",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.retailers",
            ),
        ),
        migrations.AlterField(
            model_name="fish1",
            name="user2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.fishermen",
            ),
        ),
    ]
