# Generated by Django 4.1.3 on 2022-12-30 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_fish1_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fish1",
            name="image",
        ),
    ]
